package hbm;
// Generated 28/12/2020 10:06:51 AM by Hibernate Tools 3.5.0.Final

/**
 * Usuario generated by hbm2java
 */
public class Usuario implements java.io.Serializable {

	private String email;
	private String firstName;
	private String lastName;
	private String password;
	private String phone;
	private String fax;

	public Usuario() {
	}

	public Usuario(String email) {
		this.email = email;
	}

	public Usuario(String email, String firstName, String lastName, String password, String phone, String fax) {
		this.email = email;
		this.firstName = firstName;
		this.lastName = lastName;
		this.password = password;
		this.phone = phone;
		this.fax = fax;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	@Override
	public String toString() {
		return "Usuario [email=" + email + ", firstName=" + firstName + ", lastName=" + lastName + ", password="
				+ password + ", phone=" + phone + ", fax=" + fax + "]";
	}

}
