package hbv;
// Generated 28/12/2020 01:40:11 PM by Hibernate Tools 3.5.0.Final

import java.math.BigDecimal;

/**
 * Vehicle generated by hbm2java
 */
public class Vehicle implements java.io.Serializable {

	private String vehicleNo;
	private String color;
	private BigDecimal wheel;
	private BigDecimal seat;

	public Vehicle() {
	}

	public Vehicle(String vehicleNo) {
		this.vehicleNo = vehicleNo;
	}

	public Vehicle(String vehicleNo, String color, BigDecimal wheel, BigDecimal seat) {
		this.vehicleNo = vehicleNo;
		this.color = color;
		this.wheel = wheel;
		this.seat = seat;
	}

	public String getVehicleNo() {
		return this.vehicleNo;
	}

	public void setVehicleNo(String vehicleNo) {
		this.vehicleNo = vehicleNo;
	}

	public String getColor() {
		return this.color;
	}

	public void setColor(String color) {
		this.color = color;
	}

	public BigDecimal getWheel() {
		return this.wheel;
	}

	public void setWheel(BigDecimal wheel) {
		this.wheel = wheel;
	}

	public BigDecimal getSeat() {
		return this.seat;
	}

	public void setSeat(BigDecimal seat) {
		this.seat = seat;
	}

	@Override
	public String toString() {
		return "Vehicle [vehicleNo=" + vehicleNo + ", color=" + color + ", wheel=" + wheel + ", seat=" + seat + "]";
	}

	public void setWheel(String string) {
		// TODO Auto-generated method stub
		
	}

	public void setSeat(String string) {
		// TODO Auto-generated method stub
		
	}

}
