package hbm;
// Generated 28/12/2020 01:31:55 PM by Hibernate Tools 3.5.0.Final

import java.math.BigDecimal;

/**
 * Vehicle generated by hbm2java
 */
public class Vehicle implements java.io.Serializable {

	private String vehocleNo;
	private String color;
	private BigDecimal wheel;
	private BigDecimal seal;

	public Vehicle() {
	}

	public Vehicle(String vehocleNo) {
		this.vehocleNo = vehocleNo;
	}

	public Vehicle(String vehocleNo, String color, BigDecimal wheel, BigDecimal seal) {
		this.vehocleNo = vehocleNo;
		this.color = color;
		this.wheel = wheel;
		this.seal = seal;
	}

	public String getVehocleNo() {
		return this.vehocleNo;
	}

	public void setVehocleNo(String vehocleNo) {
		this.vehocleNo = vehocleNo;
	}

	public String getColor() {
		return this.color;
	}

	public void setColor(String color) {
		this.color = color;
	}

	public BigDecimal getWheel() {
		return this.wheel;
	}

	public void setWheel(BigDecimal wheel) {
		this.wheel = wheel;
	}

	public BigDecimal getSeal() {
		return this.seal;
	}

	public void setSeal(BigDecimal seal) {
		this.seal = seal;
	}

}
