package comconf;
// Generated Dec 29, 2020, 6:24:39 PM by Hibernate Tools 3.5.0.Final

/**
 * Doctor generated by hbm2java
 */
public class Doctor implements java.io.Serializable {

	private long idDoctor;
	private String nombre;
	private String apellidos;
	private String direccion;
	private String telefono;
	private String rfc;
	private String especialidad;
	private String sexo;
	private String correo;
	private String contra;

	public Doctor() {
	}

	public Doctor(long idDoctor) {
		this.idDoctor = idDoctor;
	}

	public Doctor(String nombre, String apellidos, String direccion, String telefono, String rfc, String especialidad,
			String sexo, String correo, String contra) {
		super();
		this.nombre = nombre;
		this.apellidos = apellidos;
		this.direccion = direccion;
		this.telefono = telefono;
		this.rfc = rfc;
		this.especialidad = especialidad;
		this.sexo = sexo;
		this.correo = correo;
		this.contra = contra;
	}

	public Doctor(long idDoctor, String nombre, String apellidos, String direccion, String telefono, String rfc,
			String especialidad, String sexo, String correo, String contra) {
		this.idDoctor = idDoctor;
		this.nombre = nombre;
		this.apellidos = apellidos;
		this.direccion = direccion;
		this.telefono = telefono;
		this.rfc = rfc;
		this.especialidad = especialidad;
		this.sexo = sexo;
		this.correo = correo;
		this.contra = contra;
	}

	public long getIdDoctor() {
		return this.idDoctor;
	}

	public void setIdDoctor(long idDoctor) {
		this.idDoctor = idDoctor;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellidos() {
		return this.apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	public String getRfc() {
		return this.rfc;
	}

	public void setRfc(String rfc) {
		this.rfc = rfc;
	}

	public String getEspecialidad() {
		return this.especialidad;
	}

	public void setEspecialidad(String especialidad) {
		this.especialidad = especialidad;
	}

	public String getSexo() {
		return this.sexo;
	}

	public void setSexo(String sexo) {
		this.sexo = sexo;
	}

	public String getCorreo() {
		return this.correo;
	}

	public void setCorreo(String correo) {
		this.correo = correo;
	}

	public String getContra() {
		return this.contra;
	}

	public void setContra(String contra) {
		this.contra = contra;
	}

	@Override
	public String toString() {
		return "Doctor [idDoctor=" + idDoctor + ", nombre=" + nombre + ", apellidos=" + apellidos + ", direccion="
				+ direccion + ", telefono=" + telefono + ", rfc=" + rfc + ", especialidad=" + especialidad + ", sexo="
				+ sexo + ", correo=" + correo + ", contra=" + contra + "]";
	}

}
