alter session set "_ORACLE_SCRIPT"=true;
CREATE USER doctor IDENTIFIED BY doctor;
GRANT CONNECT,RESOURCE,DBA TO doctor;
GRANT CREATE SESSION TO doctor WITH ADMIN OPTION;
GRANT UNLIMITED TABLESPACE TO doctor;

CREATE TABLE doctor(
    id_doctor NUMBER(10)GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR(100),
    apellidos VARCHAR(250),
    direccion VARCHAR(250),
    telefono VARCHAR(250),
    rfc VARCHAR(50),
    especialidad VARCHAR(100),
    sexo VARCHAR(50),
    correo VARCHAR(100),
    contra VARCHAR(50),
    CONSTRAINT doctor_pk PRIMARY KEY (id_doctor)
);


CREATE TABLE itinerario(
    id_itinerario NUMBER GENERATED BY DEFAULT AS IDENTITY,
    no_semana NUMBER(10),
    inicioL NUMBER(10),
    terminoL NUMBER(10),
    diaLunes VARCHAR(50),
    inicioM NUMBER(10),
    terminoM NUMBER(10),
    diaMartes VARCHAR(50),
    inicioMie NUMBER(10),
    terminoMie NUMBER(10),
    diaMiercoles VARCHAR(50),
    inicioJ NUMBER(10),
    terminoJ NUMBER(10),
    diaJueves VARCHAR(50),
    inicioV NUMBER(10),
    terminoV NUMBER(10),
    diaViernes VARCHAR(50),
    id_doctor NUMBER(10), 
    CONSTRAINT itinerario_pk PRIMARY KEY(id_itinerario),
    CONSTRAINT itinerario_doctor_fk FOREIGN KEY(id_doctor) REFERENCES doctor(id_doctor)
    );